apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-apps
  namespace: argocd
spec:
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
