apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-config
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: demo-config
  source:
    path: manifests/config
    repoURL: https://github.com/pittar-gitops/99-gitops-demo.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
