apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: demo-apps
  source:
    path: manifests/apps/cicd
    repoURL: https://github.com/pittar-gitops/99-gitops-demo.git
    targetRevision: master
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
