apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/redhat-canada-gitops/10-devtools/jenkins2/overlays/m2-pvc?ref=master
- github.com/redhat-canada-gitops/10-devtools/nexus2/base?ref=master
